from rdkit import Chem
from rdkit.Chem import AllChem, Descriptors, rdMolDescriptors
from typing import List, Tuple
import torch
from torch_geometric.data import Data
#from xtb.ase.calculator import XTB
#from xtb import ase
from ase import Atoms
from ase.optimize import BFGS
import numpy as np


def save_mol_to_xyz(mol, filename):
    with open(filename, 'w') as f:
        f.write(f"{mol.GetNumAtoms()}\n")
        f.write("Generated by RDKit\n")
        for atom in mol.GetAtoms():
            pos = mol.GetConformer().GetAtomPosition(atom.GetIdx())
            f.write(f"{atom.GetSymbol():2s} {pos.x:10.6f} {pos.y:10.6f} {pos.z:10.6f}\n")


def mol_to_xyz(mol) -> List:
    xyz = []
    for atom in mol.GetAtoms():
        pos = mol.GetConformers().GetAtomPosition(atom.GetIdx())
        xyz.append(pos)
    return xyz


def format_results(results):
    output = "优化结果汇总:\n"
    for stage, result in results.items():
        status_icon = "✓" if result['status'] == 'success' else "✗"
        output += f"  {status_icon} {stage}: {result['message']}\n"
        if result['status'] == 'success':
            output += f"     能量: {result['energy']:.6f} eV, 最大力: {result['max_force']:.6f} eV/Å\n"
    return output


def rdkit_to_xtb_direct(mol, charge=0, solvent=None):
    # 使用 xtb-python API 直接在内存中计算

    # 提取原子符号和坐标
    symbols = []
    positions = []
    for atom in mol.GetAtoms():
        symbols.append(atom.GetSymbol())
        pos = mol.GetConformer().GetAtomPosition(atom.GetIdx())
        positions.append((pos.x, pos.y, pos.z))

    # 创建 ASE Atoms 对象
    atoms = Atoms(symbols=symbols, positions=positions)

    optimization_stages = [
        {"name": "普通优化", "electronic_temperature": 300, "max_iterations": 300},
        {"name": "高温优化", "electronic_temperature": 1500, "max_iterations": 500},
        {"name": "收敛优化", "electronic_temperature": 300, "max_iterations": 200},
    ]

    # 设置 xtb 计算器
    calc_kwargs = {
        'method': 'GFN2-xTB',
        'accuracy': 1.0,
        'electronic_temperature': 300,
        'max_iterations': 250,
        'charge': charge
    }

    if solvent:
        calc_kwargs['solvent'] = solvent

    results = {}

    for i, stage in enumerate(optimization_stages):
        stage_name = stage["name"]
        try:
            print(f"\n=== 第{i + 1}阶段: {stage_name} ===")
            print(f"参数: electronic_temperature={stage['electronic_temperature']}, "
                  f"max_iterations={stage['max_iterations']}")

            # 更新计算器参数
            current_kwargs = calc_kwargs.copy()
            current_kwargs.update({
                'electronic_temperature': stage['electronic_temperature'],
                'max_iterations': stage['max_iterations']
            })

            atoms.calc = XTB(**current_kwargs)
            # 优化
            opt = BFGS(atoms, trajectory=None, logfile=None)
            opt.run(fmax=0.01)

            # 记录成功信息
            energy = atoms.get_potential_energy()
            max_force = max(np.linalg.norm(force) for force in atoms.get_forces())

            results = {
                'stage': f"{stage_name}",
                'status': 'success',
                'energy': energy,
                'max_force': max_force,
                'message': f"{stage_name} 成功完成"
            }

            print(f"{stage_name}成功!")
            print(f"能量: {energy:.6f} eV")
            print(f"最大力: {max_force:.6f} eV/Å")

            if stage_name == "普通优化":
                break

        except Exception as e:
            error_msg = f"{stage_name} 失败: {str(e)}"
            print(f" {error_msg}")

            results = {
                'stage': f"{stage_name}",
                'status': 'failed',
                'error': str(e),
                'error_type': type(e).__name__,
                'message': error_msg
            }
            # 如果是最后一个阶段，直接抛出异常
            if i == len(optimization_stages) - 1:
                raise Exception(f"所有优化阶段都失败。详细错误:\n{format_results(results)}")
            # 否则继续下一个阶段
            continue

    # 获取结果
    energy = results['energy']
    # 转换为 XYZ 格式字符串
    optimized_xyz = f"{len(atoms)}\n"
    optimized_xyz += f"Optimized with xtb, energy={energy}eV\n"
    for symbol, position in zip(atoms.get_chemical_symbols(), atoms.get_positions()):
        optimized_xyz += f"{symbol:2s} {position[0]:12.6f} {position[1]:12.6f} {position[2]:12.6f}\n"

    return optimized_xyz, energy, results['status'], atoms


def check_convergence(atoms, fmax_threshold=0.01):
    # 检查几何优化是否收敛

    forces = atoms.get_forces()
    max_force = np.max(np.linalg.norm(forces, axis=1))

    convergence_info = {
        'converged': max_force < fmax_threshold,
        'max_force': max_force,
        'fmax_threshold': fmax_threshold,
        'forces': forces
    }

    return convergence_info


def generate_3d_structure(smiles, method: str = 'ETKDGv3', optimize=True):
    # 从 SMILES 创建分子并添加氢原子
    mol = Chem.MolFromSmiles(smiles)
    mol = Chem.AddHs(mol)

    # 选择构象生成方法
    if method == 'ETKDGv3':
        params = AllChem.ETKDGv3()
    elif method == 'ETKDGv2':
        params = AllChem.ETKDGv2()
    else:  # ETKDG
        params = AllChem.ETKDG()

    # 生成 3D 坐标
    success = AllChem.EmbedMolecule(mol, params)

    if success == -1:
        print("构象生成失败，尝试使用基本方法...")
        AllChem.EmbedMolecule(mol)  # 回退到基本方法

    # 可选的力场优化
    if optimize:
        try:
            # 使用 UFF 力场进行优化
            AllChem.UFFOptimizeMolecule(mol)
            print("UFF 力场优化完成")
        except:
            print("UFF 优化失败，使用 MMFF 力场...")
            try:
                AllChem.MMFFOptimizeMolecule(mol)
                print("MMFF 力场优化完成")
            except:
                print("力场优化失败，使用原始构象")

    return mol